version: "3.7"

services:
  shuup:
    build:
      context: .
      args:
        editable: 1
    command: bash -c "./runserver.sh"
    env_file:
      - .env
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - /app/.sqlite
      - /app/shuup/admin/static
      - /app/shuup/front/static
      - /app/shuup/gdpr/static
      - /app/shuup/notify/static
      - /app/shuup/regions/static
      - /app/shuup/themes/classic_gray/static
      - /app/shuup/xtheme/static
    tty: true
    restart: always
