version: "3.7"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dawasasa
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: bash -c "./runserver.sh"
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
