# Generated by Django 2.2.24 on 2021-09-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PesapalPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_reference', models.CharField(max_length=255)),
                ('pesapal_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant_used', models.BooleanField(default=False)),
                ('pesapal_status', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_url', models.TextField()),
            ],
        ),
    ]
